files:
  baseDir: /path/to/your/project
  include: 
    - "**/*.hbs"
  exclude: 
    - "**/special.hbs"
  layout: "layout.hbs"
  copy:
    - "public/favicon.ico"
  rewrite:
    compile:
      - from: ".hbs"
        to: ".html"
data:
  aKey: "aValue"
